atlantis:
  orgWhitelist: github.com/jmorgan415/wiz-atlantis-poc
  logLevel: "info"

  vcsSecretName: "atlantis-vcs"

  ## Use Server Side Repo Config,
  ## ref: https://www.runatlantis.io/docs/server-side-repo-config.html
  repoConfig: |
   ---
   repos:
   - id: github.com/jmorgan415/wiz-atlantis-poc
     apply_requirements: [approved, mergeable]
     allowed_overrides: [workflow, apply_requirements]
     # allow_custom_workflows defines whether this repo can define its own
     # workflows. If false (default), the repo can only use server-side defined
     # workflows.
     allow_custom_workflows: true
     # delete_source_branch_on_merge: true
   workflows:
     default:
       plan:
         steps:
         - init
         - plan:
             extra_args: ["-var-file", ./config.tfvars"]
       apply:
         steps:
         - run: terraform${ATLANTIS_TERRAFORM_VERSION} apply -no-color -parallelism=50 $PLANFILE
     ws:
       plan:
         steps:
         - run: terraform${ATLANTIS_TERRAFORM_VERSION} init -input=false -no-color
         - run: terraform${ATLANTIS_TERRAFORM_VERSION} workspace select -no-color ${WORKSPACE} || terraform${ATLANTIS_TERRAFORM_VERSION} workspace new ${WORKSPACE} && terraform${ATLANTIS_TERRAFORM_VERSION} workspace select -no-color ${WORKSPACE}
         - run: terraform${ATLANTIS_TERRAFORM_VERSION} plan -var-file=./config.tfvars -input=false -refresh -no-color -parallelism=50 -out $PLANFILE
       apply:
         steps:
         - run: terraform${ATLANTIS_TERRAFORM_VERSION} apply -no-color -parallelism=50 $PLANFILE

  service:
    type: LoadBalancer

  ingress:
    enabled: false

  dataStorage: 15Gi

  resources:
    requests:
      memory: 8Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 2
