account_id             = "984186218765"
account_name           = "wiz-demo-infra"
cluster_name           = "wiz-demo-infra"
cluster_version        = "1.22"
region                 = "us-east-2"
vpc_name               = "wiz-demo-infra"
