apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: atlantis-secret-store #The secret store name we have just created.
    kind: SecretStore
  target:
    name: atlantis-vcs # Secret name in k8s
  data:
  - secretKey: github_token # which key it's going to be stored
    remoteRef:
      key: atlantis # Our secret-name goes here
