apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: atlantis-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:  # set secretStore provider to AWS.
      service: SecretsManager # Configure service to be Secrets Manager
      region: us-east-2   # Region where the secret is.
      auth:
        auth:
        serviceAccount:
          name: "atlantis"
