apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-clusters
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters
    repoURL: git@github.com:jmorgan415/wiz-atlantis-poc.git
    targetRevision: main
