apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{ name }}-external-secrets'
      labels:
        app: external-secrets
    spec:
      project: default
      source:
        repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
        targetRevision: "6.3.0"
        chart: kubernetes-external-secrets
        helm:
          releaseName: external-secrets
          values: |
            env:
              AWS_REGION: "{{ metadata.annotations.awsRegion }}"
              LOG_LEVEL: "warn"
              POLLER_INTERVAL_MILLISECONDS: "30000"
            fullnameOverride: external-secrets
            replicaCount: 1
            resources:
              limits:
                cpu: 2000m
                memory: 640Mi
              requests:
                cpu: 1000m
                memory: 256Mi
            securityContext:
              fsGroup: 65534
            serviceAccount:
              annotations:
                "eks.amazonaws.com/role-arn": "arn:aws:iam::{{ metadata.annotations.awsAccountID }}:role/{{ name }}-external-secrets"
              create: true
              name: external-secrets

      destination:
        name: '{{ name }}'
        namespace: external-secrets
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
