apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
  - clusters: wiz-demo-infra 
  template:
    metadata:
      name: '{{name}}-external-secrets'
      labels:
        app: external-secrets
    spec:
      project: default
      source:
        repoURL: https://charts.external-secrets.io
        targetRevision: "v0.6.0-rc1"
        chart: external-secrets
        helm:
          releaseName: external-secrets
          values: |
            extraEnv:
              - name: AWS_REGION
                value: "{{ metadata.annotations.awsRegion }}"
              - name: LOG_LEVEL
                value: "warn"
              - name: POLLER_INTERVAL_MILLISECONDS
                value: "30000"
            fullnameOverride: external-secrets
            replicaCount: 1
            resources:
              limits:
                cpu: 2000m
                memory: 640Mi
              requests:
                cpu: 1000m
                memory: 256Mi
            podSecurityContext:
              fsGroup: 65534
            serviceAccount:
              annotations:
                "eks.amazonaws.com/role-arn": "arn:aws:iam::{{ metadata.annotations.awsAccountID }}:role/{{name}}-external-secrets"
              create: true
              name: external-secrets

      destination:
        name: '{{name}}'
        namespace: external-secrets
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
